server:
  port: 8021

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.edu.lingnan.entity    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: parkingcloud-info
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver            # mysql驱动包
    url: jdbc:mysql://192.168.1.67:3306/parking?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&useSSL=false             # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.1.128:7001/eureka/
  instance:
    instance-id: parkingcloud-provider-info-8021  #自定义服务名称信息
    prefer-ip-address: true    #访问路径可以显示IP地址
    hostname: 192.168.1.128

info:
  app.name: parkingcloud
  company.name: cn.edu.lingnan
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#pagehelper
# 指定数据库，不指定的话会默认自动检测数据库类型
pagehelper:
  helperDialect: mysql
# 是否启用分页合理化。
# 如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；
# 不启用的，以上两种情况都会返回空数据
  reasonable: true
  # 默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  supportMethodsArguments: true
  # 用于从对象中根据属性名取值，
  # 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count

#负载均衡
ribbon:
  eureka:
    enabled: true

